### ISSUE TITLE
アップロードする全画像のEXIF自動除去

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#1]
### Summary

気にする人がいた

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
ドライブの設定で「オリジナル画像を保持」を無効にしていれば、元のexifが残ることはない。
https://lo.nr1a.inc/notes/9x1nrxwigozj0mrb
