### ISSUE TITLE
ログインユーザー以外 https://yami.ski/channels を無効

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#11]
### Summary

全く外部に見せないのも怪しまれるので、こっちは公開してもいいかもしれません。

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
ユーザーのプライバシーを保護するという観点を重視するのであれば、チャンネルのTLを無効にするべきかと

**Comment by hitalin** [comment]
ユーザーに匿名アンケートすると、5人中5人ともチャンネルのTLを無効にしたいとのことなので、無効にするべきです。

**Comment by nr1a** [comment]
https://github.com/yamisskey/yamisskey/commit/c70699b7dbe2434298a340bc7e64305a19643859
