### ISSUE TITLE
ログインユーザーも以外も https://yami.ski/explore のユーザー欄をローカルもリモートも無効

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#16]
### Summary

やみすきーに誰がいて、誰とつながっているのかバレる

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
https://github.com/yamisskey/yamisskey/commit/4e764fd108d78a65b12cbe1a4d84f8f062a157d0
