### ISSUE TITLE
鍵ノートを他鯖から解錠されないようにする

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#2]
### Summary

そういう鯖がある

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
## idea
* 鍵投稿を強制的に非連合にしてしまう
e2eeとかもありな気はするけど、連合先に行っても意味がないので連合しない方がいい

**Comment by nr1a** [comment]
これは人それぞれ扱い方があるので、tipsとして流した方がいい
