### ISSUE TITLE
魚拓を撮れないようにする

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#3]
### Summary

そういう魚拓サイトがある

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
## idea
`packages/backend/src/server/api/endpoints/notes/show.ts`の`requireCredential: true`にすることでアカウントがないユーザーからの閲覧を制限することが出来る。
一般的な魚拓サイトはアカウントのログイン等は行えないため効果的。
これでいいなら変更したものを投げる

**Comment by nr1a** [comment]
帝国で採用してる方式でコミットした、これでいいならPR投げる
https://github.com/yamisskey/yamisskey/commit/98d8945ba63dbda6c63be1695a3267fce3cdaa9a

> ## idea
> `packages/backend/src/server/api/endpoints/notes/show.ts`の`requireCredential: true`にすることでアカウントがないユーザーからの閲覧を制限することが出来る。 一般的な魚拓サイトはアカウントのログイン等は行えないため効果的。 これでいいなら変更したものを投げる

**Comment by nr1a** [comment]
PR発行済み
https://github.com/yamisskey/yamisskey/pull/9
