### ISSUE TITLE
MFM検索でSearXNGを指定

### ISSUE THREAD

**Issue by hitalin** [yamisskey/yamisskey#4]
### Summary

Google検索しか使えない

### Purpose

プライバシー保護

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by nr1a** [comment]
PRを発行
https://github.com/yamisskey/yamisskey/pull/5

**Comment by hitalin** [comment]
SearXNGインスタンスを [disroot.orgのインスタンス](https://search.disroot.org/)から[yami.skiのインスタンス](https://search.yami.ski/)に変更したいです。

**Comment by nr1a** [comment]
https://github.com/yamisskey/yamisskey/blob/master/packages/frontend/src/pages/settings/general.vue#L52

**Comment by nr1a** [comment]
https://github.com/yamisskey/yamisskey/commit/3b2fb10e21350b6ed40297054cf8df80eba1451f
